### ISSUE TITLE
ScrollReveal with Masonry slight issue

### ISSUE THREAD

**Issue by MariuzM** [scrollreveal/scrollreveal#475]
Hi first of all big thanks for this cool script!!!

I know it's not your scripts fault and i just blame myself for not knowing more how to code but trying to learn. So i have website that just loads bunch of images. So i'm using Masonry to get that look and ScrollReveal fade stuff. I have noticed especially when working in Chrome Dev mode + No Cache is that some of the images are not loaded correctly looks like they are on top of each other. 

Here is the pic of the issue:
https://www.dropbox.com/s/4t5vs0725g39hqa/Screenshot%202018-11-16%20at%2010.08.30.jpg?dl=0

Also made a video:
https://www.dropbox.com/s/qzzbi6yrvv7mykr/Screen%20Recording%202018-11-16%20at%2010.53.25.mov?dl=0

Here is the full code:

HTML:
```php
<?php
$dir = "img/";
$img = glob($dir . "*.jpg");
?>

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Photography</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" media="screen" href="main.css" />

</head>

<body>

	<div class="grid">
		<div class="grid-sizer"></div>
		<?php foreach ($img as $image) {echo "<div class='grid-item'><img src='$image'></div>";}?>
	</div>

	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
	<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.js"></script>
	<script src="https://unpkg.com/scrollreveal@4.0.5/dist/scrollreveal.js"></script>
	<script src="js/main.js"></script>

</body>

</html>
```

CSS
```css
* {
  box-sizing: border-box;
}

.grid:after {
  content: '';
  display: block;
  clear: both;
}

.grid-sizer,
.grid-item {
  width: 33.333%;
  
}

.grid-item {
  float: left;
}

.grid-item img {
  display: block;
  max-width: 100%;
  transition: all 0.2s linear;
  padding: 5px 5px;

}

.grid-item img:hover {
  box-shadow: 0px 0px 40px -1px #000000bf;
  transition: all 0.2s linear;
}
```

JS
```js
var $grid = $('.grid').masonry({
  percentPosition: true,
  columnWidth: '.grid-sizer',
  itemSelector: '.grid-item'
});

$grid.imagesLoaded().progress(function () {
  $grid.masonry();
});

ScrollReveal().reveal('.grid-item', {
  delay: 100,
});
```
